### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Garrett",
  "email": "garrett@test.com",
  "password": "password",
  "password_confirmation": "password"
}